#lang sicp
(define (cont-frac n d k)
  (cond ((zero? k) 0)
        (else (/ (n k)
                 (+ (d k) (cont-frac n d (- k 1)))))))
(+ 2 (cont-frac (lambda (i) 1.0)
           (lambda (i)
             (if (= (modulo i 3) 2) (* 2 (+ 1 (quotient i 3) 1))
                 1.0))
           4000))